### ISSUE TITLE
Connection over TCP/IP

### ISSUE THREAD

**Issue by buhoba** [theendlessriver13/combilog1022#19]
Great tool, thanks! Is there a way to make a connection over TCP/IP to the Combilog ? Something like

combilog.Comblog(logger_addr=192.168.1.50, port=8000)

Best regards.

**Comment by jkittner** [comment]
I am not sure if the logger supports this way of communication for reading and setting channels at all. It does have a built in web server where you can change settings using a web interface.

Their documentation does not go into more detail than: _Communication is supported via standard interface (RS232), tel-
ephone or GSM modem or TCP/IP protocol._  This sentence is referring to their combilog GUI software though. So if it was possible it is at least not documented. 

If you know a way or have an idea on how to find out let me know.

**Comment by buhoba** [comment]
I didn't find a way to connect  through TCP/IP.  I use now a raspberry pi to get the data over USB and sending them over TCP/IP.

**Comment by jkittner** [comment]
Ah cool, that's pretty similar to the setup I am running, although my raspberry pi is also running the database. May I ask just out of curiosity in what context you are using the combilog logger and this package?  I am surprised someone actually uses this package since the logger is pretty rare outside of professional applications.

If you have any other suggestions, features or future improvements, please let me know.
